# @package _group_

common:
  fp16: true
  log_format: json
  log_interval: 200

checkpoint:
  #save_interval_updates: 25000
  save_interval_updates: 10000
  keep_interval_updates: 1
  no_epoch_checkpoints: true
  #no_epoch_checkpoints: false
  #save_interval: 100
  restore_file: "/home/wupeng/fairseq/checkpoints/wav2vec_small.pt"
  reset_optimizer: True
  save_dir: /data07/wupeng/exp/fairseq/checkponts/wav2vec2/wav2vec2_loss10_neg100_test
  patience: 50

task:
  _name: audio_pretraining_mmd_dual
  data: ???
  max_sample_size: 200000
  min_sample_size: 32000
  normalize: false

dataset:
  num_workers: 6
  max_tokens: 1400000
  skip_invalid_size_inputs_valid_test: true

distributed_training:
  distributed_world_size: 1
  #distributed_world_size: 2
  ddp_backend: legacy_ddp

criterion:
  _name: wav2vec_mmd_cls5
  infonce: true
  log_keys: ["prob_perplexity","code_perplexity","temp"]
  loss_weights: [0.1, 10, 10.0, 0.0]

optimization:
  max_update: 400000
  lr: [0.0005]
  update_freq: [64]
  #update_freq: [32]

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-06
  weight_decay: 0.01

lr_scheduler:
  _name: polynomial_decay
  warmup_updates: 32000

model:
  _name: wav2vec2mmd9content
  quantize_targets: true
  final_dim: 256
  encoder_layerdrop: 0.05
  dropout_input: 0.1
  dropout_features: 0.1
  feature_grad_mult: 0.1
  encoder_embed_dim: 768
  num_negatives_prob: 100
